### ISSUE TITLE
Option To Change Working Directory Path

### ISSUE THREAD

**Issue by El-Coder** [f5devcentral/vscode-f5-chariot#1]
I'm on a mac and run into issue since file path doesn't have quotes.  

So for example this fails:
`docker run --rm -v /Users/El-Coder/Projects/Conf:/app/data f5-appsvcs-charon:1.8.0 -o data/converted.as3.json -c data/toConvert.conf --unsupported --unsupported-objects unSupported.json`

But this works:
`docker run --rm -v "/Users/El-Coder/Projects/Conf":/app/data f5-appsvcs-charon:1.8.0 -o data/converted.as3.json -c data/toConvert.conf --unsupported --unsupported-objects unSupported.json`

So similar to how fields for the docker image and output file can be changed if there was another field for changing the file path that would be great!

**Comment by DumpySquare** [comment]
Just made some updates for you.  

Try out the latest here:  https://github.com/f5devcentral/vscode-f5-chariot/releases/tag/v0.4.0

Let me know if this fixes your issue or if we need to do more tweaking!

**Comment by El-Coder** [comment]
Perfect this works!
