### ISSUE TITLE
DO error - On conversion of UCS

### ISSUE THREAD

**Issue by AnthonyF5** [f5devcentral/vscode-f5-chariot#10]
**Error:**
Converting UCS to DO with "Convert to DO with ACC" always generates two error entries:

        "}": {
            "class": "ManagementIp",
            "address": "}"
        },

        "/Common/comm-public": {
            "source": "default",
            "class": "SnmpCommunity",
            "name": "public"
        }

**Issue:**
The first items causes and error as it is empty and should be removed.
The second entry has a "/Common/" in the name which causes an error.

**Versions:**
DO = v1.36.1
ACC = v1.21.0
VSCode = 1.83.1

**Comment by DumpySquare** [comment]
Hi @AnthonyF5.   Please see the core ACC engine project for feedback on conversions

https://github.com/f5devcentral/f5-automation-config-converter
