### ISSUE TITLE
Route conversion error when not using a gateway

### ISSUE THREAD

**Issue by AnthonyF5** [f5devcentral/vscode-f5-chariot#11]
DO version: 1.40.0
DO schema ref: https://clouddocs.f5.com/products/extensions/f5-declarative-onboarding/latest/schema-reference.html#route

**Problem:**
Converting the UCS to DO the "Route" config references a VLAN not a gateway, the conversion does not create the "target" output.

**UCS route:**
net route /Common/vMLC-vF5 { 
    description "Toward vMLC"
    interface /Common/Internal
    network 172.22.246.0/28
 }

**Generated by chariot:**
"vMLC-vF5": {
            "class": "Route",
            "network": "172.22.246.0/28"
        },

The generated content fails without the target or gw line.

**Comment by DumpySquare** [comment]
Hi @AnthonyF5.  Thanks for opening this issue.  This project only wraps the core ACC engine for use in VSCode.  Please see the original project for feedback.

https://github.com/f5devcentral/f5-automation-config-converter
