### ISSUE TITLE
requesting new functionality

### ISSUE THREAD

**Issue by sbarakett** [f5devcentral/vscode-f5-chariot#14]
When running function convert to AS3 with ACC, I would love to see these two new features.

The conversion does not include the tenants "default route domain"

what you get:
   "tenantname": {
        "class": "Tenant",
        "Shared": {

what I would like:
   "tenantname": {
        "class": "Tenant",
        "defaultRouteDomain": 1,
        "Shared": {

The conversion ignores pool members names, and just gets the IP addresses, so when pushing to a new F5, you loose the node names.

what you get from pool:
               "members": [
                    {
                        "addressDiscovery": "static",
                        "servicePort": 443,
                        "serverAddresses": [
                            "x.x.x.x",
                            "x.x.x.x"
                        ],
                        "shareNodes": true
                    }
                ],

what I would like to see:

                "members": [
                    {
                    "addressDiscovery": "static",
                    "servicePort": 443,
                    "servers":[
                        { 
                            "name": "nodename",
                            "address": "x.x.x.x" 
                        },
                        { 
                            "name": "nodename"",
                            "address": "x.x.x.x" 
                        }
                        ]
                    }
                ],

Thanks for any attention you put towards this.

**Comment by DumpySquare** [comment]
Hi @sbarakett.  Thank you for opening this issue.  Unfortunately, this project only wraps the core ACC engine for use in VSCode.  I suggest you ping the original project to see if this can be accommodated.

https://github.com/f5devcentral/f5-automation-config-converter

**Comment by sbarakett** [comment]
Great, thanks for getting back to me.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
