### ISSUE TITLE
f5-chariot using ACC 1.13 instead of latest available

### ISSUE THREAD

**Issue by rjouhann** [f5devcentral/vscode-f5-chariot#4]
Hello,

While using VS code to convert and BIG-IP config to AS3 using ACC, it looks like the extension isn't using the [latest version of ACC available on Github](https://github.com/f5devcentral/f5-as3-config-converter/releases/tag/v1.15.0) which is 1.15 today.

```
[2021-10-04T17:23:44.466Z] [INFO]: ACC Details:  {
  name: 'f5-as3-config-converter',
  author: 'F5 Networks',
  description: 'F5 AS3 Config Converter',
  version: '1.13.0',
  license: 'Apache-2.0',
  repository: 'git+https://github.com/f5devcentral/f5-as3-config-converter.git'
}
[2021-10-04T17:23:44.471Z] [INFO]: f5.chariot.convert called
```

Thanks & Regards,
Roman

**Comment by DumpySquare** [comment]
extension has been updated to latest ACC v1.15.0 and released here and marketplace.
