### ISSUE TITLE
AS3 Conversion Fails

### ISSUE THREAD

**Issue by Etherchannel01** [f5devcentral/vscode-f5-chariot#8]
When attempting to convert my virtual server configs into AS3 the following output is displayed in vscode. "ACC METADATA Undefined" 

Unsure where to proceed from where. Any help is appreciated.

**Comment by DumpySquare** [comment]
can you provide any more of the OUTPUT logs?

What version of extension are you using?

**Comment by Etherchannel01** [comment]
Here is the output from vscode. I am using extension version 1.21.0

59 [2022-08-10T20:26:01.278Z] [INFO]: f5.chariot.convertAS3 called
60 [2022-08-10T20:26:01.279Z] [INFO]: f5.chariot.convertAS3 text found
61 [2022-08-10T20:26:01.279Z] [INFO]: f5.chariot.convertAS3 converting "\r\n" to "\n"
62 [2022-08-10T20:26:01.282Z] [INFO]: ACC METADATA undefined
63 [2022-08-10T20:26:01.363Z] [INFO]: f5 atc schema injected

**Comment by mdditt2000** [comment]
@Etherchannel01 please can you send me your virtual server configs automation automation_toolchain_pm@f5.com thanks!

**Comment by mdditt2000** [comment]
Created Jira CHARON-731 task for PM tracking. Requested virtual server configs

**Comment by DumpySquare** [comment]
This tool only wraps the core ACC engine.  Please see this repo for issues.

https://github.com/f5devcentral/f5-automation-config-converter
