### ISSUE TITLE
ACC Chariot out of sync with Main code release

### ISSUE THREAD

**Issue by CarlB-dev** [f5devcentral/vscode-f5-chariot#9]
Latest release of ACC is v1.2.4 https://github.com/f5devcentral/f5-automation-config-converter/releases/tag/v1.24.0 

Can we get this extension upgraded to the most recent version of ACC?

**Comment by jasonrahm** [comment]
+1

**Comment by DumpySquare** [comment]
Not sure if/when this might happen.  closing for now.

https://github.com/f5devcentral/f5-automation-config-converter
